# HASS sensors & automation to get temperatures from the TEMPer2 sensor
# This particular sensor has USB ID:  1a86:e025
# - The -3.5, and -1.3, are correctional values
sensor:
###################################
# TEMPER DEVICE
###################################
- platform: file
  file_path: /config/files/temper2.json
  name: TEMPer2 Device
  value_template: "{{ '%0.2f'| format(value_json.Device|float - 3.5) }}"
  unit_of_measurement: '°C'
###################################
# TEMPER PROBE
###################################
- platform: file
  file_path: /config/files/temper2.json
  name: TEMPer2 Probe
  value_template: "{{ '%0.2f'| format(value_json.Probe|float - 1.3) }}"
  unit_of_measurement: '°C'
###################################
# TEMPER AUTOMATION
###################################
automation:
- id: '1588345689200'
  alias: Execute the shell script to get info from TEMPer2
  description: "Every two minutes the script is executed"
  trigger:
    - platform: template
      value_template: "{{ now().minute|int % 2 == 0 }}"
  condition: []
  action:
    - service: shell_command.temper2
      data: {}
  mode: single
###################################
# TEMPER SCRIPT
###################################
shell_command:
  temper2: bash /config/sh/temper2.sh

